[package]
name = "dds-bridge"
version = "0.1.1"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"
description = "Rusty API for DDS, the double dummy solver for bridge"
repository = "https://github.com/jdh8/dds-bridge"
license = "Apache-2.0"
categories = ["game-development"]
keywords = ["bridge", "double-dummy"]

[dependencies]
bitflags = "2.5.0"
dds-bridge-sys = "1.0.1"
rand = "0.8.5"
