[package]
name = "dds-bridge"
version = "0.10.2"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"
description = "Rusty API for DDS, the double dummy solver for bridge"
repository = "https://github.com/jdh8/dds-bridge"
license = "Apache-2.0"
categories = ["game-development"]
keywords = ["bridge", "double-dummy"]

[dependencies]
bitflags = "2.8.0"
dds-bridge-sys = "2.0.2"
once_cell = "1.20.3"
rand = "0.9.0"
regex = "1.11.1"
thiserror = "2.0.11"

[profile.dev]
opt-level = 2
